### ISSUE TITLE
Game Library page feature.

### ISSUE THREAD

**Issue by AnnikaW-dev** [AnnikaW-dev/Boardwalkgame-AW#8]
**User story:**A Game Library page, which shows four new games, and four old favourites to show customers a range of games available in the shop.

**Accaptence Critera:**
 

- [x] Show a list of new and old games that are availible in the shop 
- [x] The website has a separate page for the list of board games.
- [x] The game library page utilises the Bootstrap grid and card components for consistency in layout and responsiveness.
- [x] Each card states the relevant game title, image, descriptions, number of players and age range.

**Task** 

- [x] Create a responsive Game Library page featuring a handful of selected games and their relevant details.
